services:
  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS='true'
    ports:
      - 18888:18888
      - 4317:18889
    restart: no
    container_name: dashboard

